# -*- coding: utf-8 -*-
"""Stack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EU2BPTqJpB5LSLCHhNUyQTk3dYHqYQV_
"""

class Stack:

    def __init__(self):
        self.stack = []
    
    def isEmpty(self):
        return self.stack == []
    
    def pop(self):
        if len(self.stack) < 1:
            return None
        return self.stack.pop()
    
    def top(self):
      # temp = len(stack)
      return self.stack[len(self.stack)-1]

    def push(self, item):
        self.stack.append(item)

    def size(self):
        return len(self.stack)
    
    def print_Stack(self):
      print(self.stack)

stack_1 = Stack()

stack_1.push("hello")
stack_1.push("world")
stack_1.push("hy,  I am Abdul Jabbar")
stack_1.print_Stack()
print(stack_1.pop())
stack_1.print_Stack()
stack_1.top()

