# -*- coding: utf-8 -*-
"""Queue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbYgMbFMQ-NtxOuGc4lpNer5SU9OAVlp
"""

class Queue:

    def __init__(self):
        self.queue = []

    def isEmpty(self):
        return self.queue == []
    
    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        if len(self.queue) < 1:
            return None
        return self.queue.pop(0)

    def top(self):
      return self.queue[0]

    def size(self):
        return len(self.queue) 
    
    def rear(self):
        return self.queue[self.size()-1]
    
    def print_Stack(self):
      print(self.queue)


queue_1 = Queue()

queue_1.enqueue([3,4,5,6,7])
queue_1.enqueue("hello")
queue_1.enqueue("world")
queue_1.enqueue("hy")
queue_1.enqueue(224)
queue_1.enqueue(4.34)
# queue_1.enqueue([3,4,5,6,7])
queue_1.print_Stack()
# queue_1.dequeue()
# queue_1.print_Stack()
# queue_1.isEmpty()
b = queue_1.top()
a = queue_1.rear()
print(a)
print(b)